# -*- coding: utf-8 -*-
"""assignment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjZACkGHtHBMI_gyxqn166CYVbeq4xd-

1. Create the below pattern using nested for loop in Python.
*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*
"""

for i in range(1,6):
    for j in range(i):
        print("*",end="")
    print()
for k in range(4,0,-1):
    for j in range(k):
        print("*",end="")
    print()

"""2.Write a Python program to reverse a word after accepting the input from the user.
Sample Output:
Input word: ineuron
Output: norueni
"""

x=input("enter a word")
print(x[::-1])